const assert=require('node:assert/strict');
const C=require('./can.js');
assert.equal(C.hex(0x1fffffff),'0x1FFFFFFF');
assert.throws(()=>C.packet({mode:'NORMAL',ids:[],candidates:[]}));
assert.throws(()=>C.packet({mode:'LISTEN_ONLY',ids:new Array(129),candidates:[]}));
assert.equal(C.packet({mode:'LISTEN_ONLY',ids:[],candidates:[]}).ids.length,0);
assert.equal(C.driverStates.DISABLED,'CAN ปิดอยู่');
assert.equal(C.driverStates.LISTENING,'เปิดตัวรับแล้ว · Listen-only');
assert.match(C.diagnosis({driver_state:'START_FAILED',start_error:257}),/257/);
assert.match(C.diagnosis({enabled:false}),/ยังไม่เปิด/);
assert.match(C.diagnosis({enabled:true,acquiring:false}),/พัก/);
assert.match(C.diagnosis({enabled:true,acquiring:true,rx_session_frames:0}),/ยังไม่มีเฟรม/);
assert.match(C.diagnosis({enabled:true,acquiring:true,rx_session_frames:10,last_rx_age_ms:3000}),/เกิน 2/);
assert.match(C.diagnosis({enabled:true,acquiring:true,rx_session_frames:10,last_rx_age_ms:20}),/พบ CAN traffic/);
console.log('PASS: listen-only CAN mode, bounded payloads, logger controls and hexadecimal identifiers');
