const assert=require('node:assert/strict');
const C=require('./can.js');
assert.equal(C.hex(0x1fffffff),'0x1FFFFFFF');
assert.equal(C.capture('throttle',10),'EXPERIMENT THROTTLE 10');
assert.equal(C.capture('',10,true),'BASELINE 10');
for(const seconds of [0,-1,3601,1.2,NaN,Infinity,'1x'])assert.throws(()=>C.capture('ACTION',seconds));
for(const label of ['', 'has space','a'.repeat(24),'<script>','label\nSTOP'])assert.throws(()=>C.capture(label,10));
assert.throws(()=>C.packet({mode:'NORMAL',ids:[],candidates:[]}));
assert.throws(()=>C.packet({mode:'LISTEN_ONLY',ids:new Array(129),candidates:[]}));
assert.throws(()=>C.packet({mode:'LISTEN_ONLY',ids:[],candidates:new Array(13)}));
assert.equal(C.packet({mode:'LISTEN_ONLY',ids:[],candidates:[]}).ids.length,0);
assert.equal(C.driverStates.DISABLED,'CAN ปิดอยู่');
assert.equal(C.driverStates.LISTENING,'เปิดตัวรับแล้ว · Listen-only');
assert.match(C.diagnosis({driver_state:'START_FAILED',start_error:257}),/257/);
assert.match(C.diagnosis({enabled:false}),/ยังไม่เปิด/);
assert.match(C.diagnosis({enabled:true,acquiring:false}),/พัก/);
assert.match(C.diagnosis({enabled:true,acquiring:true,rx_session_frames:0}),/ยังไม่มีเฟรม/);
assert.match(C.diagnosis({enabled:true,acquiring:true,rx_session_frames:10,last_rx_age_ms:3000}),/เกิน 2/);
assert.match(C.diagnosis({enabled:true,acquiring:true,rx_session_frames:10,last_rx_age_ms:20}),/พบ CAN traffic/);
console.log('PASS: exclusive CAN mode, bounded payloads, controls, experiment durations/labels, hexadecimal identifiers');
